export const TRIGGER_NAMES = {
  NAME_PICKER: 'NAME_PICKER',
  CLASS_PICKER: 'CLASS_PICKER',
  SPECIES_PICKER: 'SPECIES_PICKER',
  LINEAGE_PICKER: 'LINEAGE_PICKER',
  BACKGROUND_PICKER: 'BACKGROUND_PICKER',
  FEAT_PICKER: 'FEAT_PICKER',
  CLASS_FEATURE_PICKER: 'CLASS_FEATURE_PICKER',
  SPECIES_FEATURE_PICKER: 'SPECIES_FEATURE_PICKER',
  SPELL_PICKER: 'SPELL_PICKER',
  GEAR_PICKER: 'GEAR_PICKER',

} as const;

export type TriggerName = typeof TRIGGER_NAMES[keyof typeof TRIGGER_NAMES];